export const SAVE_USER = 'save_user' //保存用户
export const SET_USER = 'set_user' //重置用户
export const SAVE_TOKEN = 'save_token'//保存token
export const SET_TOKEN = 'set_token'//重置token
export const ADD_CART = 'add_cart' //添加到购物车
export const RESET_CART = 'reset_cart' //清空购物车
export const DEL_CART = 'del_cart' //删除购物车选项
export const UPDATE_COUNT = 'update_count' //更新购物车商品个数
export const ADD_ORDER = 'add_order' //添加订单
export const DEL_ORDER = 'del_order' //删除订单